#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

$app = \P2pmessenger\P2pmessenger\core\App::getInstance(new \P2pmessenger\P2pmessenger\core\config\Config([
    'core' => [
        'timezone' => 'UTC',
        'memoryLimit' => '128M',
    ],
    'router' => [
        'basedir' => __DIR__,
        'folders' => [
            'ssl',
        ],
    ],
]));
$app->init();